workflows:
    react-native-ios:
        name: iOS Build
        max_build_duration: 120
        instance_type: mac_mini_m1
        vars:
          BUNDLE_ID: 'org.reactjs.native.example.Wobble'
          XCODE_WORKSPACE: 'Wobble.xcoworkspace'
          XCODE_SCHEME: 'wobble'
        environment:
          node: v16.11.1
          xcode: latest
          cocoapods: default
        scripts:
            - name: Install npm dependencies
              script: |
                npm install
            - name: Install CocoaPods dependencies
              script: |
                cd ios && pod install
            - name: Set up code signing settings on Xcode project
              script: |
                xcode-project use-profiles --warn-only
            - name: Build ipa for distribution
              script: |
                xcode-project build-ipa \
                  --workspace "$CM_BUILD_DIR/ios/$XCODE_WORKSPACE" \
                  --scheme "$XCODE_SCHEME"
        artifacts:
            - build/ios/ipa/*.ipa
            - /tmp/xcodebuild_logs/*.log
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM